// Components
export { default as App } from "./mainPage/App"
export { default as NavBar } from "./mainPage/nav"
export { default as Link } from "./Link"
export { default as Style } from "../styles/App.css"
export { default as NavbarContainer } from "./mainPage/NavbarContainer"
export { default as Logo } from "./mainPage/Logo"
export { default as LeftSide } from "./mainPage/LeftSide"
export { default as RightSide } from "./mainPage/RightSide"
export { default as FeaturesContainer } from "./mainPage/FeaturesContainer"
export { default as LanguageContainer } from "./mainPage/languageContainer"
export { default as AboutUs } from "./mainPage/aboutUs"
export { default as CreateProject } from "./createProject/createProject"
export { default as Project } from "./project"
export { default as SelectLang } from "./createProject/selectLang"
export { default as BtnContainer } from "./createProject/btnContainer"
export { default as FinishForm } from "./createProject/finishForm"
export { default as BackWrapper } from "./mainPage/backWrapper"
export { default as LockedStatus } from './projectStatus/lockedStatus'
export { default as NotFound } from './mainPage/notFound'
export { default as ProjectStatus } from './projectStatus/projectStatus'
export { default as LoginPanel } from './admin/login/'
export { default as AdminPanel } from './admin/panel/' 
export { default as Nav } from './admin/panel/nav'
export { default as Dashboard } from './admin/panel/dashboard/'
export { default as Orders } from './admin/panel/orders/'
export { default as Vistors } from './admin/panel/vistors'
export { default as OrdersContainer } from './admin/panel/orders/ordersContainer'
export { default as VistorsContainer } from './admin/panel/vistors/vistorsContainer'
export { default as DashboardContainer } from './admin/panel/dashboard/dashboardContainer'
export { default as Auth } from '../auth'
export { default as schema } from '../components/createProject/validationShema'
export { default as AlreadyLogged} from './projectStatus/alreadyLogged'

// icons
export { default as Home } from "../imgs/h-i.svg"
export { default as HowTo } from "../imgs/i-i.svg"
export { default as ActiveHome } from "../imgs/h-i-a.svg"
export { default as logo } from "../imgs/logo.png"
export { default as LeftSideImg } from "../imgs/leftSide.gif"
export { default as RightArrow } from "../imgs/ra-i.svg"
export { default as LogoInfo } from "../imgs/logo-info.png"
export { default as Fb } from "../imgs/fb-i.svg"
export { default as tw } from "../imgs/tw-i.svg"
export { default as Ld } from "../imgs/li-i.svg"
export { default as select } from "../imgs/select.svg"
export { default as clapping } from "../imgs/clapping.svg"
export { default as write } from "../imgs/write.svg"
export { default as strong } from "../imgs/strong.svg"
export { default as positive } from "../imgs/positive.svg"
export { default as like } from "../imgs/like.svg"
export { default as beg } from "../imgs/beg.svg"
export { default as downArrow } from "../imgs/d-ar.svg"
export { default as Js } from "../imgs/js-i.svg"
export { default as Php } from "../imgs/php-i.svg"
export { default as Loader } from "../imgs/loader.svg"
export { default as success } from "../imgs/success.svg"
export { default as error } from "../imgs/error.svg"
export { default as check } from "../imgs/check.svg"
export { default as lock } from '../imgs/lock.svg'
export { default as notfound } from '../imgs/notfound.gif'
export { default as user } from '../imgs/man.svg'
export { default as support } from '../imgs/support.svg'
export { default as rightArrow } from '../imgs/right-arrow.svg'
export { default as locked } from '../imgs/locked.svg'